name: bridges_gps
description: A new Flutter project.
version: 1.0.0+2
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.4.0
  location: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
